### ISSUE TITLE
Configure APIs

### ISSUE THREAD

**Issue by DAM-96** [StitchCodes/hunger-managment#8]
# Story
As a developer, I want to be able to use the Spoonacular and TheCocktailDB APIs inside the code, so that I can get information from the application through specific queries

# Requirements
- The Spoonacular API returns a list of dishes upon sending a list of ingredients
- The CocktailDB API returns a drink suggestion after sending the name of a dish

**Comment by StitchCodes** [comment]
API's are currently working as expected. Closign issue.
